name: learn_what_is_stream
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  flutter_screenutil: ^5.4.0+1

  # Cache
    ## Generic cache manager for flutter.
    ## Saves web files on the storages of the device
    ## and saves the cache info using sqflite.
  flutter_cache_manager: ^3.3.0
    
  # Firebase
  firebase_core: ^1.10.0
  firebase_analytics: ^9.1.4
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.7
  cloud_functions: ^3.2.6
  firebase_messaging: ^11.2.13
  firebase_storage: ^10.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true